version: "3.7"

services:

  redis:
    image: redis:3.2
    container_name: superset_cache
    restart: unless-stopped
    networks:
      - visortech_network
    ports:
      - "127.0.0.1:6490:6379"
    volumes:
      - redis:/data

  db:
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

    image: postgres:10
    container_name: postgres
    restart: unless-stopped
    networks:
      - visortech_network
    ports:
      - "127.0.0.1:6543:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

  superset:
    container_name: visortech_superset_0.37.2
    command: ["flask", "run", "-p", "8088", "--with-threads", "--reload", "--debugger", "--host=0.0.0.0"]
    restart: unless-stopped
    build:
      args:
        NPM_BUILD_CMD: build
        SUPERSET_PORT: 8088
        CLOUDSDK_PYTHON: /usr/bin/python3
      context: ./
      dockerfile: Dockerfile-visortech
    ports:
      - 8005:8088
    depends_on:
      - db
      - redis
    networks:
      - visortech_network
    volumes:
      - ./docker/docker-init.sh:/app/docker-init.sh
      - ./docker/pythonpath_dev:/app/pythonpath
      - ./superset:/app/superset
      - ./superset-frontend:/app/superset-frontend
      - superset_home:/app/superset_home
    environment:
      - COMPOSE_PROJECT_NAME=superset

      # database configurations (do not modify)
      - DATABASE_DB=superset
      - DATABASE_HOST=db
      - DATABASE_PASSWORD=superset
      - DATABASE_USER=superset

      # database engine specific environment variables
      # change the below if you prefers another database engine
      - DATABASE_PORT=${POSTGRES_PORT}
      - DATABASE_DIALECT=postgresql
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

      #MYSQL_DATABASE=superset
      #MYSQL_USER=superset
      #MYSQL_PASSWORD=superset
      #MYSQL_RANDOM_ROOT_PASSWORD=yes

      # Add the mapped in /app/pythonpath_docker which allows devs to override stuff
      - PYTHONPATH=/app/pythonpath:/app/pythonpath_docker

      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}

      - FLASK_ENV=production
      - SUPERSET_ENV=production
      - SUPERSET_LOAD_EXAMPLES=no

networks:
  visortech_network:
    external: false
    labels:
      - "com.visortechsolutions.description=Infrastructure Network"


volumes:
  superset:
    external: false
  postgres:
    external: false
  redis:
    external: false
